[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'postgresql']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn twenty_one_tech_pocs.wsgi:application --bind 0.0.0.0:$PORT' 