[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn twenty_one_tech_pocs.wsgi:application --bind 0.0.0.0:$PORT' 