[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn twenty_one_tech_pocs.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 