services:
  twenty_one_tech_pocs:
    build: .
    container_name: django_app
    ports:
      - "8001:8000" # Changed host port from 8000 to 8001
    env_file:
      - ../.env
    environment:
      - ES_URL=http://elasticsearch:9200
      # - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - elasticsearch
      # - ollama
    volumes:
      - ../twenty_one_tech_pocs:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - tech

  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS http://localhost:9200/_cluster/health | grep -qE '(green|yellow)' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - tech

  ollama:
    image: ollama/ollama:0.5.7
    container_name: ollama
    ports:
      - "11435:11434"
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - tech

volumes:
  es_data:
  ollama_data:


networks:
  tech:
    driver: bridge
